services:
  check-cpf:
    image: ${IMAGE_NAME}:${TAG}
    container_name: ${SERVICE_NAME}
    restart: unless-stopped

    env_file:
      - .env

    expose:
      - "${PORT}"

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${DOMAIN}`)"
      - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=${PORT}"
      - "traefik.http.routers.${SERVICE_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${SERVICE_NAME}.tls.certresolver=letsencrypt"

    networks:
      - api-cpf-net

networks:
  api-cpf-net:
    external: true