name: Build Check Digitos CPF

on:
  push:
    paths:
      - 'api-check-cpf/**'
    tags:
      - 'cpf-v*.*.*'

permissions:
  contents: read
  packages: write

jobs:

  build:
    name: Build Check Digitos CPF
    # This job uses a reusable workflow to build the Docker image for the Check Digitos CPF service.
    uses: ./.github/workflows/reusable-build.yml

    with:
      image_name: api-check-cpf
      context: ./api-check-cpf
      dockerfile: ./api-check-cpf/Dockerfile
      tag_prefix: cpf-v