```yaml
name: Build Check Digitos CPF

on:
  push:
    paths:
      - 'api-check-cpf/**'
    tags:
      - 'cpf-v*.*.*'

jobs:

  build:
    name: Build Check Digitos CPF

    uses: ./.github/workflows/reusable-build.yml

    with:
      image_name: check-digitos-cpf
      context: ./api-check-cpf
      dockerfile: ./api-check-cpf/Dockerfile
      tag_prefix: cpf-v

    secrets:
      GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
